apiVersion: v1
kind: Service
metadata:
  name: {{ include "videoserver.fullname" . }}
  labels:
    {{- include "videoserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: rtmp
  selector:
    {{- include "videoserver.selectorLabels" . | nindent 4 }}

